server:
  port: ${PORT:0}

eureka:
  instance:
    preferIpAddress: true
    nonSecurePort: ${PORT:0}
    hostname: ${DOMAIN}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/

spring:
  application:
    name: dtservicetemplate
  profiles:
    active: ${ARCH_ENV}
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: dtarchconfig