server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
  instance:
    hostname: ${DOMAIN:localhost}
    nonSecurePort: ${PORT:0}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: dtservicetemplate
  profiles:
    active: ${ARCH_ENV}
  cloud:
    config:
      profile: ${ARCH_ENV}
      discovery:
        enabled: true
        serviceId: dtarchconfig